### ISSUE TITLE
Create slideshow presentation to guide our first presentation -presentation

### ISSUE THREAD

**Issue by eloketobe** [zuri-training/anima_lib_team98#12]

**Comment by OreRuth** [comment]
I was able to create a slide show for the first presentation from the team, using Google Slides.
Attached is the link to the file
https://docs.google.com/presentation/d/1CFhPjg0-gzRZR8ouazsL2Rg89qL1bt6MxAdxnsRSEsg/edit#slide=id.gfdbfcb7440_0_12

**Comment by eloketobe** [comment]
Thanks

**Comment by TomiEtta** [comment]
I reviewed and made minor edits to the slideshow as well as advised the presenter on what to say. This advice was basically for her to speak on what we understand the problem is, what we are doing to solve that problem, and what is left for us to do.

[This is a link to the slideshow](https://docs.google.com/presentation/d/1CFhPjg0-gzRZR8ouazsL2Rg89qL1bt6MxAdxnsRSEsg/edit?usp=sharing)
