### ISSUE TITLE
Convert low fidelity designs to high fidelity -Design

### ISSUE THREAD

**Issue by eloketobe** [zuri-training/anima_lib_team98#14]
convert the earlier designed low fidelity screens to high fidelity.

**Comment by debbyCokes** [comment]
As a product designer, I want my design screens to allow realistic user interaction while obeying aesthetic usability effect rule, so that users and developers don't have difficulty interacting with it as they would the final product.

[page to high fidelity designs](https://www.figma.com/file/mnP49B5GDsVrVBPIp1Q6g0/Animax-Project-Design?node-id=604%3A980)

**Comment by eloketobe** [comment]
welldone Cokes

**Comment by debbyCokes** [comment]
Thank you boss.

**Comment by Voiced-debug** [comment]
I created the documentation page to guide developers on how to use the animation library.

**Comment by starjosh48** [comment]
I changed 2 of the documentation pages Lofi to High fidelity
[Link to the 1st page](https://www.figma.com/file/mnP49B5GDsVrVBPIp1Q6g0/Animax-Project-Design?node-id=2439%3A12557)
[link to the 2nd page](https://www.figma.com/file/mnP49B5GDsVrVBPIp1Q6g0/Animax-Project-Design?node-id=2439%3A13346)

**Comment by TomiEtta** [comment]
I converted the low-fidelity designs for the animation preview page https://github.com/zuri-training/anima_lib_team98/issues/24 and the download page https://github.com/zuri-training/anima_lib_team98/issues/64. The high-fidelity designs were easier to do because the low-tech design helped with visualizing the design, flow and experience for each screen.

These are the lo-fi links to the [Animation page](https://www.figma.com/file/mnP49B5GDsVrVBPIp1Q6g0/Animax-Project-Design?node-id=619%3A1013) and [Download page](https://www.figma.com/file/mnP49B5GDsVrVBPIp1Q6g0/Animax-Project-Design?node-id=508%3A743)

These are the hi-fi links to the [Animation page](https://www.figma.com/file/mnP49B5GDsVrVBPIp1Q6g0/Animax-Project-Design?node-id=2439%3A12614) and [Download page](https://www.figma.com/file/mnP49B5GDsVrVBPIp1Q6g0/Animax-Project-Design?node-id=2439%3A12102)

**Comment by VicRoosevelt** [comment]
I converted the low-fidelity design for the forgot password page to high fidelity [link to high-fidelity forgot password page](https://www.figma.com/file/mnP49B5GDsVrVBPIp1Q6g0/Animax-Project-Design?node-id=2439%3A12229)

**Comment by eloketobe** [comment]
I converted the homepage low fidelity design to high fidelity design and made changes and improvements where necessary. I also designed the homepage to have an authenticated and unauthenticated variant.
These are the links to the high fidelity screens: [Authenticated homepage](https://www.figma.com/file/mnP49B5GDsVrVBPIp1Q6g0/Animax-Project-Design?node-id=2439%3A13883) and [Unauthenticated homepage](https://www.figma.com/file/mnP49B5GDsVrVBPIp1Q6g0/Animax-Project-Design?node-id=2505%3A12591)
