### ISSUE TITLE
Design new proposed animation screen with the variations for each animation -design

### ISSUE THREAD

**Issue by eloketobe** [zuri-training/anima_lib_team98#24]
You do not have to delete the recent one, just create another next to it. 
the variations would differ too, e.g the variation for bounce would be the speed of the bounce, the variation of the rotation would be the direction and angle of rotation, e.t.c
Come up with a way to demonstrate this

**Comment by TomiEtta** [comment]
The original design was completely fine, but it had to be edited to accommodate the new variations added by the developers.

 The goal here was to ensure the user isn't overburdened by too many choices, so what I did was focus on the important touchpoints, making them larger/bolder than other parts. Generally, I added only the necessary functions on this page such as the animated content itself, the animation type, the preview options, copy code option and the favourite option. Navigation was also made simple, after all, that is the goal of Animax. 

Lastly, I also designed an unauthenticated version because only authenticated users can customize the animation preview page.

[This is the link to an authenticated animation preview page](https://www.figma.com/file/mnP49B5GDsVrVBPIp1Q6g0/Animax-Project-Design?node-id=2439%3A12614)

[This is the link to an unauthenticated animation preview page](https://www.figma.com/file/mnP49B5GDsVrVBPIp1Q6g0/Animax-Project-Design?node-id=2439%3A12631)
